services:
  eventstore:
    image: eventstore/eventstore:21.2.0-buster-slim
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      EVENTSTORE_INSECURE: true
      EVENTSTORE_ENABLE_EXTERNAL_TCP: true
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true

  readmodel_sqlserver:
    build:
      context: ./docker/readmodel/
      dockerfile: Dockerfile
    ports:
      - 1433:1433