version: '3'
services:
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    container_name: devopen_eventstore
    environment:
      - EVENTSTORE_EXT_IP_ADVERTISE_AS=127.0.0.1
      - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
    ports:
     - 1113:1113
     - 2113:2113
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    networks: 
      devopennetwork:
        aliases: 
          - eventstore
  readmodel_sqlserver:
    build:
      context: .
      dockerfile: docker/readmodel/dockerfile
    container_name: readmodel_sqlserver
    ports:
      - 1433:1433
    healthcheck:
      test: sqlcmd -S readmodel -U SA -P 'GqMxaCiCKEzWTT6hdMwBDArb7ZnHboVmawNgL7YFkNU2A' -Q 'select 1'
      interval: 10s
      timeout: 5s
    networks:
      devopennetwork:
        aliases:
          - readmodel

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - devopennetwork

  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   ports:
  #     - 9201:9200
  #   networks:
  #     - devopennetwork

  # es03:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   ports:
  #     - 9202:9200
  #   networks:
  #     - devopennetwork

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - devopennetwork

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  devopennetwork:
    driver: bridge