FROM mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

ENV PATH="/opt/mssql-tools/bin:${PATH}"

COPY docker/readmodel/sql/ /opt/mssql-scripts/

ENV SA_PASSWORD=GqMxaCiCKEzWTT6hdMwBDArb7ZnHboVmawNgL7YFkNU2A
ENV ACCEPT_EULA=Y

RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 20 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'GqMxaCiCKEzWTT6hdMwBDArb7ZnHboVmawNgL7YFkNU2A' -i /opt/mssql-scripts/*.sql \
    && pkill sqlservr
