FROM mcr.microsoft.com/mssql/server:2022-RTM-CU2-ubuntu-20.04

COPY ./sql/ /opt/mssql-scripts/

ENV SA_PASSWORD=GqMxaCiCKEzWTT6hdMwBDArb7ZnHboVmawNgL7YFkNU2A
ENV ACCEPT_EULA=Y

RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 15 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -i /opt/mssql-scripts/0_create_db.sql \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -d ReadModel -i /opt/mssql-scripts/1_create_tables.sql \
    && pkill sqlservr

HEALTHCHECK --interval=10s --timeout=3s --start-period=10s --retries=10 \
  CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT 1" -b -o /dev/null